title: Curriculum Vitae
url: 'https://padoim.com'

description: A beautiful Jekyll theme for creating resume
theme_skin: ceramic # blue turquoise green berry orange ceramic
chrome_mobile_color: "#545e6c"

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
